#!/usr/bin/python

import csv
import json
import argparse

parser = argparse.ArgumentParser(description='Build a hypertree from description.')
parser.add_argument('basename', type=str,
                  	help='base name of the CSV file to read')

args = parser.parse_args()

BASENAME = args.basename
INFILE = BASENAME + '.csv'
JSFILE = BASENAME + '.js'
HTMLFILE = BASENAME + '.html'

infile = csv.DictReader(open(INFILE))
lines = list(infile)

nodes=[]
for line in lines:
    # update edges depending on what's in each node
    node={"id": line["ID"], "name": line["Name"],
    	"data": {"text": line["Text"]},
        "adjacencies": []}
    nodes.append(node)
for line in lines:
    if line["To"]:
        id_from=line["ID"]
        id_to=line["To"]
        for node in nodes:
            if node["id"] == id_to:
                if line["Type"] == 'R':
                    node["adjacencies"].append({"nodeTo": id_from,
                                                "data": {"weight": 1,
                                                         "$color": "#f00",
                                                         '$arg_type': 'refute',
                                                         '$arc_start': id_from}})
                else:
                    node["adjacencies"].append({"nodeTo": id_from,
                                                "data": {"weight": 1,
                                                         '$arg_type': 'support',
                                                         '$arc_start': id_from}})
            if node["id"] == id_from:
                if line["Type"] == 'R':
                    node["adjacencies"].append({"nodeTo": id_to,
                                                "data":{"weight": 1,
                                                        "$color": "#f00",
                                                        '$arg_type': 'refute',
                                                        '$arc_start': id_from}})
                else:
                    node["adjacencies"].append({"nodeTo": id_to,
                                                "data": {"weight": 1,
                                                         '$arg_type': 'support',
                                                         '$arc_start': id_from}})

with open(JSFILE, 'w') as f:
    with open('hypertree-preamble.txt') as p:
        f.write(p.read())
    json.dump(nodes, f, indent=4)
    with open('hypertree-postamble.txt') as p:
        f.write(p.read())

with open(HTMLFILE, 'w') as f:
    with open('hypertree-html-preamble.txt') as p:
        f.write(p.read())
    f.write(JSFILE)
    with open('hypertree-html-postamble.txt') as p:
        f.write(p.read())
